export const NOT_VALID_JSON = 'Sorry, but input isn\'t valid json'
export const NO_DOMAIN = 'Sorry, but i can\'t fetch from nowhere'
export const NO_ENDPOINT = 'Sorry, but there isn\'t such endpoint'
export const NO_RESPONSE = 'Sorry, but server answer in not Response'
export const NO_API = 'Sorry but there isn\'t Api'
export const HAS_SYMBOL = 'Sorry, but i can\'t work this Symbols now'
export const SHOULD_DEFINE_API = 'Sorry, but you should define Api to use'
